== Что это

Проект переделки светодиодной настольной лампы ULTRA.

== Возможности

* Управление яркостью при помощи аппаратных кнопок.
* Управление яркостью с инфракрасного ПДУ.
* Обучение (программирование) под конкретный ПДУ. Для каждого из 3 действий (увеличение яркости, уменьшение яркости, вкл/выкл) предусмотрено хранение до 5 кнопок пульта.
* Работа с ПДУ, рассчитанными на частоту 36 КГц.

== Параметры лампы

Вход: +12В 1А

== Железо

Arduino nano.

== Требования
Для работы необходимы библиотеки *IRRemote* (тестировалось с версией 2.8.0) и *https://github.com/AlexGyver/GyverLibs/releases/download/GyverButton/GyverButton.zip[GyverButton]*.

IRRemote устанавливается так:

Скетч -> Подключить библиотеку -> Управлять библиотеками

Ввести в поиске "IRRemote" и установить.

GyverButton нужно скачать как zip файл и добавить так:
Скетч -> Подключить библиотеку -> Добавить zip-библиотеку. Или вручную, распаковав zip в c:\Users\<username>\Documents\Arduino\libraries


== Управление:
.В режиме обычной работы
[options="header"]
|===
|Действие           |Кнопка
|Уменьшение яркости |краткое нажатие MINUS
|Увеличение яркости |краткое нажатие PLUS
|Выключение         |длительное нажатие MINUS
|Полная яркость     |длительное нажатие PLUS
|Вход в режим обучения |трижды нажать MINUS, затем удерживать MINUS
|===

.В режиме обучения
[options="header"]
|===
|Действие |Кнопка
|Переход к обучению следующему действию |краткое нажатие PLUS
|Выход из режима обучения |трижды нажать MINUS, затем удерживать MINUS
|===

== Режим обучения
При входе в режим обучения из рабочего режима лампа включает режим обучения уменьшению яркости. Это подтверждается индикацией - плавным снижением яркости до нуля. При нажатии на кнопку ПДУ, если команда дошла и распознана, лампа дважды коротко мигнёт.

После выхода из режима обучения новые команды ПДУ будут записаны в EEPROM. Если новых команд не было (т.е. если нажимались уже выученные кнопки ПДУ), то запись не произойдёт (для экономии ресурса записи EEPROM)

.Индикация действий:
[options="header"]
|===
|Действие |Индикация
|Вход в режим обучения действию "уменьшение яркости" | плавное снижение яркости с максимума до нуля
|Вход в режим обучения действию "увеличение яркости" | плавное увеличение яркости с нуля до максимума
|Вход в режим обучения действию "ON/OFF" | Мигание 3 раза
|Выход из обучения (возврат к нормальной работе) | Быстрое мигание 5 раз
|Подтверждение распознания команды ПДУ (в режиме обучения) | Быстрое мигание 2 раза
|===

== Отладка
В файле lamp-remote-control.h можно раскомментировать **#define DEBUG** и перекомпилировать проект. Тогда при подключенном к компу Arduino можно увидеть отладочные сообщения, в т.ч. коды команд ПДУ.
